import { useEffect, useState } from 'react'
import { Bug, FolderOpen, Gauge, Server, ShieldAlert, Wifi } from 'lucide-react'
import projectApi from '../../services/projectApi'
import assetApi from '../../services/assetApi'
import vulnerabilityApi from '../../services/vulnerabilityApi'
import riskApi from '../../services/riskApi'
import scanApi from '../../services/scanApi'
function Card({ label, value, icon: Icon, tone = 'text-slate-100', loading }) { return <div className="card p-5"><div className="flex items-start justify-between"><div><p className="text-[11px] uppercase tracking-wider text-slate-500">{label}</p>{loading ? <div className="mt-3 h-8 w-16 animate-pulse rounded bg-slate-800" /> : <p className={`mt-2 text-2xl font-bold ${tone}`}>{value ?? '--'}</p>}</div><Icon className="h-5 w-5 text-sky-400" /></div></div> }
export default function OverviewCards() { const [data, setData] = useState({}); const [loading, setLoading] = useState(true); useEffect(() => { Promise.allSettled([projectApi.list({ per_page: 1 }), assetApi.stats(), vulnerabilityApi.stats(), riskApi.stats(), scanApi.list({ per_page: 5 })]).then(([p,a,v,r,s]) => { const scans = s.status === 'fulfilled' ? (s.value.data.scans || []) : []; const last = scans.find(x => x.status === 'completed'); setData({ projects: p.status === 'fulfilled' ? p.value.data.total : null, assets: a.status === 'fulfilled' ? a.value.data.total_assets : null, live: a.status === 'fulfilled' ? a.value.data.active_assets : null, critical: v.status === 'fulfilled' ? v.value.data.critical : null, risk: r.status === 'fulfilled' ? r.value.data.overall_risk_score : null, last: last?.completed_at || last?.created_at || null }) }).finally(() => setLoading(false)) }, []); const last = data.last ? new Date(data.last).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : '--'; return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card label="Total Projects" value={data.projects} icon={FolderOpen} loading={loading} /><Card label="Total Assets" value={data.assets} icon={Server} loading={loading} /><Card label="Live Assets" value={data.live} icon={Wifi} loading={loading} /><Card label="Critical Vulnerabilities" value={data.critical} icon={Bug} tone="text-red-300" loading={loading} /><Card label="Overall Risk Score" value={data.risk} icon={ShieldAlert} tone="text-amber-300" loading={loading} /><Card label="Last Scan Time" value={last} icon={Gauge} loading={loading} /></div> }
